#!/bin/bash
# hello script to run upon logging onto mallowPi
# Set default folder upon running
# Activate bashrc
# Mount all network drives
#
# Writting by Roger Dalupang
#
# Date: August 7, 2015
#
## Add commands here ##
cd /
. /etc/bash.bashrc
sudo mount -a
#service samba status
######################

## Add Welcome Statement here ##
## Anything you want to display to the user ##
echo "==Processes Status=="
service samba status
echo " "
echo "mallowPi has now been initialized..."
echo "========Welcome"  $USER"========"
#echo "===================================="
